# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
# C964

title: Computer Science Capstone
author: Dr. Jim Ashe
logo: ./url_images/3d_regression.png
# logo: ./url_images/WGU-logo-crossed-out.png
# logo: ./_static/WGU-logo-crossed-out.png
# logo-alt-text: HELLO

# alt_text: A crossed out WGU logo. Underneath the logo a caption reads this website is NOT an official resource WGU resource! It is developed by course faculty with +20 years of experience supporting C964. 
#this doesn't work? default alt is logo
#SEE: https://github.com/pydata/pydata-sphinx-theme/pull/893
#currently shows as 'alt="logo' which sphinx default when no alt is set for the logo.https://github.com/executablebooks/jupyter-book/blob/master/jupyter_book/config.py
#also see: 

#https://github.com/executablebooks/jupyter-book/issues/1783

#https://jupyterbook.org/en/stable/structure/configure.html#disable-building-files-that-arent-in-the-table-of-contents
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
    - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ashejim/C964  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)
  # path_to_book: docs  # Optional path to your book, relative to the repository root

launch_buttons:
  colab_url: "https://colab.research.google.com"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# See https://jupyterbook.org/en/stable/advanced/html.html?highlight=google_analytics#enable-google-analytics
html:
  use_issues_button: true
  use_repository_button: true
  # home_page_in_navbar: true # Whether to include your home page in the left Navigation Bar
  google_analytics_id: G-H4N36TZQ78 
  comments:
    utterances:
      repo: "github-org/github-repo"

# Add a bibtex file so that we can create cited ..
# In _config.yml
# sphinx:
#   config:
#     bibtex_reference_style: author_year
#     bibtex_bibfiles: references.bib